@enum SoPlex_BoolParamEnum::UInt32 begin
    LIFTING = 0
    EQTRANS = 1
    TESTDUALINF = 2
    RATFAC = 3
    ACCEPTCYCLING = 4
    RATREC = 5
    POWERSCALING = 6
    RATFACJUMP = 7
    ROWBOUNDFLIPS = 8
    PERSISTENTSCALING = 9
    FULLPERTURBATION = 10
    ENSURERAY = 11
    FORCEBASIC = 12
    SIMPLIFIER_SINGLETONCOLS = 13
    SIMPLIFIER_CONSTRAINTPROPAGATION = 14
    SIMPLIFIER_PARALLELROWDETECTION = 15
    SIMPLIFIER_PARALLELCOLDETECTION = 16
    SIMPLIFIER_SINGLETONSTUFFING = 17
    SIMPLIFIER_DUALFIX = 18
    SIMPLIFIER_FIXCONTINUOUS = 19
    SIMPLIFIER_DOMINATEDCOLS = 20
    ITERATIVE_REFINEMENT = 21
    ADAPT_TOLS_TO_MULTIPRECISION = 22
    PRECISION_BOOSTING = 23
    BOOSTED_WARM_START = 24
    RECOVERY_MECHANISM = 25
    BOOLPARAM_COUNT = 26
end

@enum SoPlex_IntParamEnum::UInt32 begin
    OBJSENSE = 0
    REPRESENTATION = 1
    ALGORITHM = 2
    FACTOR_UPDATE_TYPE = 3
    FACTOR_UPDATE_MAX = 4
    ITERLIMIT = 5
    REFLIMIT = 6
    STALLREFLIMIT = 7
    DISPLAYFREQ = 8
    VERBOSITY = 9
    SIMPLIFIER = 10
    SCALER = 11
    STARTER = 12
    PRICER = 13
    RATIOTESTER = 14
    SYNCMODE = 15
    READMODE = 16
    SOLVEMODE = 17
    CHECKMODE = 18
    TIMER = 19
    HYPER_PRICING = 20
    RATFAC_MINSTALLS = 21
    LEASTSQ_MAXROUNDS = 22
    SOLUTION_POLISHING = 23
    PRINTBASISMETRIC = 24
    STATTIMER = 25
    MULTIPRECISION_LIMIT = 26
    STORE_BASIS_SIMPLEX_FREQ = 27
    INTPARAM_COUNT = 28
end

@enum SoPlex_SenseEnum::Int32 begin
    OBJSENSE_MINIMIZE = -1
    OBJSENSE_MAXIMIZE = 1
end

@enum SoPlex_RepresentationEnum::UInt32 begin
    REPRESENTATION_AUTO = 0
    REPRESENTATION_COLUMN = 1
    REPRESENTATION_ROW = 2
end

@enum SoPlex_AlgorithmEnum::UInt32 begin
    ALGORITHM_PRIMAL = 0
    ALGORITHM_DUAL = 1
end

@enum SoPlex_FactorEnum::UInt32 begin
    FACTOR_UPDATE_TYPE_ETA = 0
    FACTOR_UPDATE_TYPE_FT = 1
end

@enum SoPlex_VerbosityEnum::UInt32 begin
    VERBOSITY_ERROR = 0
    VERBOSITY_WARNING = 1
    VERBOSITY_DEBUG = 2
    VERBOSITY_NORMAL = 3
    VERBOSITY_HIGH = 4
    VERBOSITY_FULL = 5
end

@enum SoPlex_SimplifierEmnum::UInt32 begin
    SIMPLIFIER_OFF = 0
    SIMPLIFIER_INTERNAL = 3
    SIMPLIFIER_PAPILO = 2
    SIMPLIFIER_AUTO = 1
end

@enum SoPlex_ScalarEnum::UInt32 begin
    SCALER_OFF = 0
    SCALER_UNIEQUI = 1
    SCALER_BIEQUI = 2
    SCALER_GEO1 = 3
    SCALER_GEO8 = 4
    SCALER_LEASTSQ = 5
    SCALER_GEOEQUI = 6
end

@enum SoPlex_StarterEnum::UInt32 begin
    STARTER_OFF = 0
    STARTER_WEIGHT = 1
    STARTER_SUM = 2
    STARTER_VECTOR = 3
end

@enum SoPlex_PricerEnum::UInt32 begin
    PRICER_AUTO = 0
    PRICER_DANTZIG = 1
    PRICER_PARMULT = 2
    PRICER_DEVEX = 3
    PRICER_QUICKSTEEP = 4
    PRICER_STEEP = 5
end

@enum SoPlex_RatioTestEnum::UInt32 begin
    RATIOTESTER_TEXTBOOK = 0
    RATIOTESTER_HARRIS = 1
    RATIOTESTER_FAST = 2
    RATIOTESTER_BOUNDFLIPPING = 3
end

@enum SoPlex_SyncModeEnum::UInt32 begin
    SYNCMODE_ONLYREAL = 0
    SYNCMODE_AUTO = 1
    SYNCMODE_MANUAL = 2
end

@enum SoPlex_ReadModeEnum::UInt32 begin
    READMODE_REAL = 0
    READMODE_RATIONAL = 1
end

@enum SoPlex_SolveModeEnum::UInt32 begin
    SOLVEMODE_REAL = 0
    SOLVEMODE_AUTO = 1
    SOLVEMODE_RATIONAL = 2
end

@enum SoPlex_CheckModeEnum::UInt32 begin
    CHECKMODE_REAL = 0
    CHECKMODE_AUTO = 1
    CHECKMODE_RATIONAL = 2
end

@enum SoPlex_TimerEnum::UInt32 begin
    TIMER_OFF = 0
    TIMER_CPU = 1
    TIMER_WALLCLOCK = 2
end

@enum SoPlex_HyperPricingEnum::UInt32 begin
    HYPER_PRICING_OFF = 0
    HYPER_PRICING_AUTO = 1
    HYPER_PRICING_ON = 2
end

@enum SoPlex_PolishEnum::UInt32 begin
    POLISHING_OFF = 0
    POLISHING_INTEGRALITY = 1
    POLISHING_FRACTIONALITY = 2
end

@enum SoPlex_RealParamEnum::UInt32 begin
    FEASTOL = 0
    OPTTOL = 1
    EPSILON_ZERO = 2
    EPSILON_FACTORIZATION = 3
    EPSILON_UPDATE = 4
    EPSILON_PIVOT = 5
    INFTY = 6
    TIMELIMIT = 7
    OBJLIMIT_LOWER = 8
    OBJLIMIT_UPPER = 9
    FPFEASTOL = 10
    FPOPTTOL = 11
    MAXSCALEINCR = 12
    LIFTMINVAL = 13
    LIFTMAXVAL = 14
    SPARSITY_THRESHOLD = 15
    REPRESENTATION_SWITCH = 16
    RATREC_FREQ = 17
    MINRED = 18
    REFAC_BASIS_NNZ = 19
    REFAC_UPDATE_FILL = 20
    REFAC_MEM_FACTOR = 21
    LEASTSQ_ACRCY = 22
    OBJ_OFFSET = 23
    MIN_MARKOWITZ = 24
    SIMPLIFIER_MODIFYROWFAC = 25
    PRECISION_BOOSTING_FACTOR = 26
    REALPARAM_COUNT = 27
end

@enum SoPlex_VarStatusEnum::UInt32 begin
    ON_UPPER = 0
    ON_LOWER = 1
    FIXED = 2
    ZERO = 3
    BASIC = 4
    UNDEFINED = 5
end

@enum SoPlex_StatusEnum::Int32 begin
    ERROR = -15
    NO_RATIOTESTER = -14
    NO_PRICER = -13
    NO_SOLVER = -12
    NOT_INIT = -11
    ABORT_CYCLING = -8
    ABORT_TIME = -7
    ABORT_ITER = -6
    ABORT_VALUE = -5
    SINGULAR = -4
    NO_PROBLEM = -3
    REGULAR = -2
    RUNNING = -1
    UNKNOWN = 0
    OPTIMAL = 1
    UNBOUNDED = 2
    INFEASIBLE = 3
    INForUNBD = 4
    OPTIMAL_UNSCALED_VIOLATIONS = 5
end

const SoPlex_RatIntType = Clong

const SOPLEX_VERSION_MAJOR = 7

const SOPLEX_VERSION_MINOR = 0

const SOPLEX_VERSION_PATCH = 0

const SOPLEX_VERSION_SUB = 0

const SOPLEX_VERSION_API = 11

const SOPLEX_WITH_BOOST = nothing

const SOPLEX_WITH_CPPMPF = nothing

const SOPLEX_WITH_GMP = nothing

const SOPLEX_WITH_ZLIB = nothing

